### ISSUE TITLE
Feature request: 3D printable case

### ISSUE THREAD

**Issue by JustGitting** [e-radionicacom/Inkplate-6-hardware#1]
Hi,

It is fantastic to see a free and open source e-reader using recycled parts. Well done!

Would you be able to add a basic 3D printable case design for Inkplate in the future? 

Thanks!

**Comment by davidzovko** [comment]
Thank you on praises, @JustGitting! 

3D printable case is logical follow up, we will publish one on our crowdfunding campaign in the following weeks: https://www.crowdsupply.com/e-radionica/inkplate-6

.stl files will be added to this repo as well.

David

**Comment by davidzovko** [comment]
Hey, files for the case has been added! We will update the 3D design file as it evolves.
