### ISSUE TITLE
Wi-Fi antenna enhancement

### ISSUE THREAD

**Issue by jf1452** [e-radionicacom/Inkplate-6-hardware#12]
Not so much of an issue, but more of a recommendation for an enhancement.

The stock PCB Wi-Fi antenna on the ESP32 does not provide very good reception, I modified mine by changing the antenna link and hardwiring an old router antenna. (Move R15 to position R14)

![IMG-5932](https://user-images.githubusercontent.com/2996505/97900116-85800380-1d3a-11eb-980b-c08e56c37324.jpg)

I stripped the antenna from the plastic case to make it fit better into the case and glued it to the side.

![IMG-5931](https://user-images.githubusercontent.com/2996505/97900194-a2b4d200-1d3a-11eb-9933-a21eb4f71405.jpg)

If I had a spare SMA connector I would have soldered that to the board and used the plug / socket rather than my bodge of hard wiring.

**Comment by davidzovko** [comment]
Thanks on your report. I would say this mostly depends on your WiFi setup and signal strength. This is the first report about WiFi reception issues regarding Inkplate that I see. 

What you have done is the correct was to add an external antenna and can be done in cases when reception is weak. We will add this info to the official documentation soon.
