### ISSUE TITLE
6Color specs not available anywhere

### ISSUE THREAD

**Issue by omnigrok** [e-radionicacom/Inkplate-6-hardware#17]
Hi,

I've been looking around for the design files for the 6Color, and can't find them. Most things I've found for other board (6Plus, 10) mention the MCP23107 IO expander, but the back of my board labels those GPIO pins as being behind a PCAL6416AHF expander instead, so I can't rely on those specs.

Do you have the actual specs for the 6Color available somewhere?

Thanks

**Comment by ifadiga** [comment]
Hello, 
Sorry for the late response, we were working on the documentation and now we published files for Inkplate 6Color.
https://github.com/SolderedElectronics/Soldered-Inkplate-6COLOR-hardware-design

**Comment by omnigrok** [comment]
Thank you!
