### ISSUE TITLE
What is the open hardware license?

### ISSUE THREAD

**Issue by JustGitting** [e-radionicacom/Inkplate-6-hardware#2]
Hi,

The open source license for the hardware seems to be missing. If you have not selected a specific hardware license yet, I suggest the TARP license as it protects users freedom, just like other software copy-left license (e.g. GPL)  

The TAPR Open Hardware License
https://tapr.org/?page_id=5968

For example the EEZ Bench Box 3 (https://www.crowdsupply.com/envox/eez-bb3) uses the license.

Cheers

**Comment by davidzovko** [comment]
Great tip, thanks, I have added [LICENSE.txt](https://github.com/e-radionicacom/Inkplate-6-hardware/blob/master/LICENSE.txt) file to the repo.

**Comment by JustGitting** [comment]
Fantastic, thanks David.
