### ISSUE TITLE
Idea: Type-C USB

### ISSUE THREAD

**Issue by craftbyte** [e-radionicacom/Inkplate-6-hardware#4]
USB Type C connectors are being used more and more in the hardware industry (even RPi 4 has switched). It would be a logical idea for a new product like Inkplate to use USB-C instead of microUSB for longevity reasons (since unlike microUSB, with USB-C the cable deteriorates instead of the plug). Would it be possible to get an Inkplate v2 with a USB-C connector?

**Comment by davidzovko** [comment]
Thanks for your suggestion, Anže. We agree and have already implemented USB-C for the future version.
