### ISSUE TITLE
New 3D printable case

### ISSUE THREAD

**Issue by jf1452** [e-radionicacom/Inkplate-6-hardware#8]
Whilst I like the design of the other 3D printable case; I did have some difficulties with it not having space for a battery, and for my poorly aligned printer, I has some issues joining the front and the back which gave me an opportunity to learn how to use FreeCad.

I attach my alternative new designs in FreeCad and stl formats for others to use; to assemble you just need some 10mm plastic standoffs. unfortunately, the holes are not quite in the right place (I think the technical drawings are not quite correct for hole and port alignment) I overcame this by drilling the PCB holes to 3.5mm which allowed it to fit.

[3D printable case.zip](https://github.com/e-radionicacom/Inkplate-6-hardware/files/5335798/3D.printable.case.zip)

**Comment by davidzovko** [comment]
Hello, yes indeed, the printer really needs to be really nicely aligned to fit top and bottom pieces. 

If you can fix the model to fit the board without drilling the holes, we will add your design to the git into community designs folder so anyone can use it. 

Thanks!
